_S(DL_ELFHDR_OK, "")
_S(DL_ELFHDR_ERR_ELFMAG,     N_("invalid ELF header"))
_S(DL_ELFHDR_ERR_CLASS32,    N_("wrong ELF class: ELFCLASS32"))
_S(DL_ELFHDR_ERR_CLASS64,    N_("wrong ELF class: ELFCLASS64"))
_S(DL_ELFHDR_ERR_BENDIAN,    N_("ELF file data encoding not big-endian"))
_S(DL_ELFHDR_ERR_LENDIAN,    N_("ELF file data encoding not little-endian"))
_S(DL_ELFHDR_ERR_EIVERSION,  N_("ELF file version ident does not match current one"))
_S(DL_ELFHDR_ERR_OSABI,      N_("ELF file OS ABI invalid"))
_S(DL_ELFHDR_ERR_ABIVERSION, N_("ELF file ABI version invalid"))
_S(DL_ELFHDR_ERR_PAD,        N_("nonzero padding in e_ident"))
_S(DL_ELFHDR_ERR_VERSION,    N_("ELF file version does not match current one"))
_S(DL_ELFHDR_ERR_TYPE,       N_("only ET_DYN and ET_EXEC can be loaded"))
_S(DL_ELFHDR_ERR_PHENTSIZE,  N_("ELF file's phentsize not the expected size"))
_S(DL_ELFHDR_ERR_INTERNAL,   N_("internal error"))
